name: Build

on:
  push:
    branches:
    - main
  # pull_request:
  #   branches:
  #   - main

# defaults:
#   run:
#     working-directory: ./mongodb

jobs:
# Runs all steps on the VM
# The service containers will use host port binding instead of container networking so you access them via localhost rather than the service name
  build:
    runs-on: ubuntu-latest

    services:
      browserless:
        image: browserless/chrome:1.49-chrome-stable
        ports:
          - 3000/tcp

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
          # cache: 'npm'

      - run: npm install
      - run: node downloader.js
        env:
          BROWSERLESS_PORT: ${{ job.services.browserless.ports[3000] }}
          USER: ${{ secrets.GOANYWHERE_USERNAME }}
          PASS: ${{ secrets.GOANYWHERE_PASSWORD }}
      - run: ls
      - uses: docker/setup-buildx-action@v1.5.1
      - uses: docker/setup-qemu-action@v1.2.0

      - name: Login to dockerhub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v3.5.0
        with:
            # ${{ github.repository }}
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=sha,format=long
            type=edge,branch=$repo.default_branch
      - name: build+push
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

