name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      browserless:
        image: browserless/chrome:1.49-chrome-stable
        ports:
          - 3000/tcp

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
          cache: 'npm'

      - run: npm install
      - run: node downloader.js
        env:
          BROWSERLESS_PORT: ${{ job.services.browserless.ports[3000] }}
          USER: ${{ secrets.GOANYWHERE_USERNAME }}
          PASS: ${{ secrets.GOANYWHERE_PASSWORD }}
      - run: ls

      - name: Login to dockerhub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: buildtag
        run: |
          echo "::set-output name=BUILD_TAG::centos-$(head -n 1 Dockerfile | sed 's/FROM centos://' | sed 's/ as build//')-$(cat version | sed 's/gagateway//' | sed 's/_linux_x64.sh//' | sed 's/_/./g')"
          echo "::set-output name=APP_VERSION::$(cat version | sed 's/gagateway//' | sed 's/_linux_x64.sh//' | sed 's/_/./g')"

      - id: docker_meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=sha,format=long
            type=edge,branch=$repo.default_branch
            type=raw,value=${{ steps.buildtag.outputs.BUILD_TAG }}
            type=raw,value=${{ steps.buildtag.outputs.APP_VERSION }}

      - name: build+push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=registry,ref=user/app:buildcache
          cache-to: type=registry,ref=user/app:buildcache,mode=max
          
      - name: Update repo description
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}

      - uses: actions/github-script@v5
        if: github.ref == 'refs/heads/main'
        env:
          TAG: ${{ steps.buildtag.outputs.BUILD_TAG }}
        with:
          script: |
            try {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${process.env.TAG}`,
                sha: context.sha
              })
            } catch (error) {
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${process.env.TAG}`,
                sha: context.sha
              })
            }